# Generated by Django 5.1.1 on 2024-12-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
