# Generated by Django 5.1.1 on 2024-12-10 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_playlist_songs_alter_song_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='song_playlists', to='project.song'),
            preserve_default=False,
        ),
    ]
