# Generated by Django 5.1.1 on 2024-12-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_song_playlist_remove_playlist_songs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='albums', to='project.song'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='numSongs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
